1.3.1

In [73]:
import numpy as np
import numpy.random as rnd

A = (np.arange(0,64) % 2).reshape(8,8)#[[(j+i) % 2 for j in range(0,8)] for i in range(0,8)]
A

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]], dtype=int32)

1.3.2

In [58]:
A = [np.arange(0,5) for _ in range(0,5)]
A

[array([0, 1, 2, 3, 4]),
 array([0, 1, 2, 3, 4]),
 array([0, 1, 2, 3, 4]),
 array([0, 1, 2, 3, 4]),
 array([0, 1, 2, 3, 4])]

1.3.3

In [65]:
A = rnd.randint(10,size=(3,3,3))
A

array([[[6, 3, 1],
        [6, 3, 2],
        [4, 9, 3]],

       [[4, 3, 6],
        [1, 9, 1],
        [8, 9, 7]],

       [[8, 1, 2],
        [0, 5, 2],
        [5, 9, 5]]])

1.3.4

In [26]:
w,h = 5,8
A = [[1 if (i <= 0 or j <= 0 or i >= h-1 or j >= w-1) else 0 for j in range(0,w)] for i in range(0,h)]
A

[[1, 1, 1, 1, 1],
 [1, 0, 0, 0, 1],
 [1, 0, 0, 0, 1],
 [1, 0, 0, 0, 1],
 [1, 0, 0, 0, 1],
 [1, 0, 0, 0, 1],
 [1, 0, 0, 0, 1],
 [1, 1, 1, 1, 1]]

1.3.5 

In [68]:
A = rnd.randint(10,size=15)
print(A)
A.sort()
B = A[::-1]
print(B)

[7 4 3 5 3 9 1 0 7 2 0 0 6 6 2]
[9 7 7 6 6 5 4 3 3 2 2 1 0 0 0]


1.3.6

In [71]:
A = rnd.randint(10,size=(rnd.randint(3,9),rnd.randint(3,9)))
w,h = len(A[0]),len(A)
print("Квадратная " if w == h else "Прямоугольная ",w,"x",h)
A

Прямоугольная  4 x 5


array([[9, 1, 6, 4],
       [8, 8, 9, 3],
       [4, 4, 4, 8],
       [3, 0, 2, 0],
       [3, 4, 5, 0]])

2.3.1

In [127]:
import pandas as pd

data = pd.read_csv("titanic.csv")
data.dropna()
data["PClass"] = pd.factorize(data["PClass"])[0]
data["Name"] = pd.factorize(data["Name"])[0]
data["Sex"] = pd.factorize(data["Sex"])[0]
i,j = rnd.randint(0,len(data)),rnd.randint(0,len(data))

dist = 0
for col in data.columns:
    dist += (data[col].values[i] - data[col].values[j]) ** 2
np.sqrt(dist)

387.229905869885

2.3.2

In [128]:
data = pd.read_csv("baby.csv")

data

year     name gender    count
0       2000    Emily      F  25956.0
1       2000   Hannah      F  23082.0
2       2000  Madison      F  19968.0
3       2000   Ashley      F  17997.0
4       2000    Sarah      F  17702.0
...      ...      ...    ...      ...
468182  2014    Nicki      F     15.0
468183  2014     Nima      F     15.0
468184  2014     Nita      F     15.0
468185  2014   Niveah      F     15.0
468186     2      NaN    NaN      NaN

[468187 rows x 4 columns]

2.3.3

In [129]:
data.head(2)

year    name gender    count
0  2000   Emily      F  25956.0
1  2000  Hannah      F  23082.0

In [130]:
data.tail(3)

year    name gender  count
468184  2014    Nita      F   15.0
468185  2014  Niveah      F   15.0
468186     2     NaN    NaN    NaN

In [131]:
data.shape

(468187, 4)

In [132]:
data.describe()

year          count
count  468187.000000  468186.000000
mean     2006.789531     116.921463
std         5.002868     787.553184
min         2.000000       5.000000
25%      2003.000000       7.000000
50%      2007.000000      12.000000
75%      2010.000000      30.000000
max      2014.000000   34477.000000

In [134]:
data.iloc[1:4]

year     name gender    count
1  2000   Hannah      F  23082.0
2  2000  Madison      F  19968.0
3  2000   Ashley      F  17997.0

In [136]:
data[data["year"] >= 2004].head(2)

year   name gender    count
121795  2004  Emily      F  25037.0
121796  2004   Emma      F  21607.0

3.3.2

In [146]:
from sklearn import preprocessing

data = pd.read_csv("iris.csv")
data["sepal_length_cm"] = preprocessing.MinMaxScaler(feature_range=(0,1)).fit_transform(data[["sepal_length_cm"]])
data["sepal_width_cm"] = preprocessing.StandardScaler().fit_transform(data[["sepal_width_cm"]])
data

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]